// This is a stupid test!// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifdef RANDOMIZE_REG_INIT
  `define RANDOMIZE
`endif // RANDOMIZE_REG_INIT
`ifdef RANDOMIZE_MEM_INIT
  `define RANDOMIZE
`endif // RANDOMIZE_MEM_INIT

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifdef RANDOMIZE
  `ifdef VERILATOR
    `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
  `else  // VERILATOR
    `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
  `endif // VERILATOR
`else  // RANDOMIZE
  `define INIT_RANDOM_PROLOG_
`endif // RANDOMIZE

module AXIStreamReceiver(	// <unknown>:90:10
  input         clock,
                reset,
                AXI_SLAVE_TVALID,
  input  [39:0] AXI_SLAVE_TDATA,
  input  [4:0]  AXI_SLAVE_TSTRB,
                AXI_SLAVE_TKEEP,
  input         AXI_SLAVE_TLAST,
                AXI_SLAVE_TUSER,
                AXI_SLAVE_TDEST,
                AXI_SLAVE_TID,
                out_ready,
  output        AXI_SLAVE_TREADY,
                out_valid,
                out_bits_last,
  output [39:0] out_bits_bits);

  wire [4:0] _fifo_q_io_deq_bits_strb;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  wire [4:0] _fifo_q_io_deq_bits_keep;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  wire       _fifo_q_io_deq_bits_user;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  wire       _fifo_q_io_deq_bits_dest;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  wire       _fifo_q_io_deq_bits_id;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  wire [6:0] _fifo_q_io_count;	// src/main/scala/chisel3/util/Decoupled.scala:375:21
  Queue fifo_q (	// src/main/scala/chisel3/util/Decoupled.scala:375:21
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (AXI_SLAVE_TVALID),
    .io_enq_bits_data (AXI_SLAVE_TDATA),
    .io_enq_bits_strb (AXI_SLAVE_TSTRB),
    .io_enq_bits_keep (AXI_SLAVE_TKEEP),
    .io_enq_bits_last (AXI_SLAVE_TLAST),
    .io_enq_bits_user (AXI_SLAVE_TUSER),
    .io_enq_bits_dest (AXI_SLAVE_TDEST),
    .io_enq_bits_id   (AXI_SLAVE_TID),
    .io_deq_ready     (out_ready),
    .io_enq_ready     (AXI_SLAVE_TREADY),
    .io_deq_valid     (out_valid),
    .io_deq_bits_data (out_bits_bits),
    .io_deq_bits_strb (_fifo_q_io_deq_bits_strb),
    .io_deq_bits_keep (_fifo_q_io_deq_bits_keep),
    .io_deq_bits_last (out_bits_last),
    .io_deq_bits_user (_fifo_q_io_deq_bits_user),
    .io_deq_bits_dest (_fifo_q_io_deq_bits_dest),
    .io_deq_bits_id   (_fifo_q_io_deq_bits_id),
    .io_count         (_fifo_q_io_count)
  );
endmodule


