// This is a stupid test!// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifdef RANDOMIZE_REG_INIT
  `define RANDOMIZE
`endif // RANDOMIZE_REG_INIT
`ifdef RANDOMIZE_MEM_INIT
  `define RANDOMIZE
`endif // RANDOMIZE_MEM_INIT

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifdef RANDOMIZE
  `ifdef VERILATOR
    `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
  `else  // VERILATOR
    `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
  `endif // VERILATOR
`else  // RANDOMIZE
  `define INIT_RANDOM_PROLOG_
`endif // RANDOMIZE

module SPNController(	// <unknown>:298:10
  input         clock,
                reset,
                AXI_SLAVE_TVALID,
  input  [39:0] AXI_SLAVE_TDATA,
  input  [4:0]  AXI_SLAVE_TSTRB,
                AXI_SLAVE_TKEEP,
  input         AXI_SLAVE_TLAST,
                AXI_SLAVE_TUSER,
                AXI_SLAVE_TDEST,
                AXI_SLAVE_TID,
                AXI_MASTER_TREADY,
  output        AXI_SLAVE_TREADY,
                AXI_MASTER_TVALID,
  output [31:0] AXI_MASTER_TDATA,
  output [3:0]  AXI_MASTER_TSTRB,
                AXI_MASTER_TKEEP,
  output        AXI_MASTER_TLAST,
                AXI_MASTER_TUSER,
                AXI_MASTER_TDEST,
                AXI_MASTER_TID);

  reg         fifo_io_enq_valid_r_31;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_bits_last_r_31;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  wire [31:0] _fifo_io_enq_bits_bits_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:78:43
  wire [7:0]  _body_io_in_4_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
  wire [7:0]  _body_io_in_3_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
  wire [7:0]  _body_io_in_2_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
  wire [7:0]  _body_io_in_1_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
  wire [7:0]  _body_io_in_0_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
  wire        canEnqueue;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:65:28
  wire        _body_io_rst_T = reset;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:61:24
  wire        _body_io_clk_T_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:60:24
  wire        _fifo_io_enq_ready;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
  wire        _fifo_io_deq_valid;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
  wire        _fifo_io_deq_bits_last;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
  wire [31:0] _fifo_io_deq_bits_bits;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
  wire [6:0]  _fifo_io_count;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
  wire [30:0] _body_out;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:59:20
  wire        _sender_in_ready;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:57:22
  wire        _receiver_out_valid;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24
  wire        _receiver_out_bits_last;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24
  wire [39:0] _receiver_out_bits_bits;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24
  AXIStreamReceiver receiver (	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24
    .clock            (clock),
    .reset            (reset),
    .AXI_SLAVE_TVALID (AXI_SLAVE_TVALID),
    .AXI_SLAVE_TDATA  (AXI_SLAVE_TDATA),
    .AXI_SLAVE_TSTRB  (AXI_SLAVE_TSTRB),
    .AXI_SLAVE_TKEEP  (AXI_SLAVE_TKEEP),
    .AXI_SLAVE_TLAST  (AXI_SLAVE_TLAST),
    .AXI_SLAVE_TUSER  (AXI_SLAVE_TUSER),
    .AXI_SLAVE_TDEST  (AXI_SLAVE_TDEST),
    .AXI_SLAVE_TID    (AXI_SLAVE_TID),
    .out_ready        (canEnqueue),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:75:22
    .AXI_SLAVE_TREADY (AXI_SLAVE_TREADY),
    .out_valid        (_receiver_out_valid),
    .out_bits_last    (_receiver_out_bits_last),
    .out_bits_bits    (_receiver_out_bits_bits)
  );
  AXIStreamSender sender (	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:57:22
    .clock             (clock),
    .reset             (reset),
    .AXI_MASTER_TREADY (AXI_MASTER_TREADY),
    .in_valid          (_fifo_io_deq_valid),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
    .in_bits_last      (_fifo_io_deq_bits_last),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
    .in_bits_bits      (_fifo_io_deq_bits_bits),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
    .AXI_MASTER_TVALID (AXI_MASTER_TVALID),
    .AXI_MASTER_TDATA  (AXI_MASTER_TDATA),
    .AXI_MASTER_TSTRB  (AXI_MASTER_TSTRB),
    .AXI_MASTER_TKEEP  (AXI_MASTER_TKEEP),
    .AXI_MASTER_TLAST  (AXI_MASTER_TLAST),
    .AXI_MASTER_TUSER  (AXI_MASTER_TUSER),
    .AXI_MASTER_TDEST  (AXI_MASTER_TDEST),
    .AXI_MASTER_TID    (AXI_MASTER_TID),
    .in_ready          (_sender_in_ready)
  );
  spn_body body (	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:59:20
    .clk      (_body_io_clk_T_1),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:60:24
    .rst      (_body_io_rst_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:61:24
    .in_0     (_body_io_in_0_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
    .in_1     (_body_io_in_1_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
    .in_2     (_body_io_in_2_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
    .in_3     (_body_io_in_3_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
    .in_4     (_body_io_in_4_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:73:44
    .out_prob (_body_out)
  );
  wire        _body_io_clk_T = clock;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:60:24
  assign _body_io_clk_T_1 = _body_io_clk_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:60:24
  Queue_2 fifo (	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (fifo_io_enq_valid_r_31),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    .io_enq_bits_last (fifo_io_enq_bits_last_r_31),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    .io_enq_bits_bits (_fifo_io_enq_bits_bits_T),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:78:43
    .io_deq_ready     (_sender_in_ready),	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:57:22
    .io_enq_ready     (_fifo_io_enq_ready),
    .io_deq_valid     (_fifo_io_deq_valid),
    .io_deq_bits_last (_fifo_io_deq_bits_last),
    .io_deq_bits_bits (_fifo_io_deq_bits_bits),
    .io_count         (_fifo_io_count)
  );
  reg  [15:0] itemCountInPipeline;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36
  wire [16:0] _canEnqueue_T = 17'h1 + {1'h0, itemCountInPipeline};	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36, :65:33
  wire [15:0] _canEnqueue_T_1 = _canEnqueue_T[15:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:65:33
  wire [16:0] _canEnqueue_T_2 = {1'h0, _canEnqueue_T_1} + {10'h0, _fifo_io_count};	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:63:20, :65:{33,55}
  wire [15:0] _canEnqueue_T_3 = _canEnqueue_T_2[15:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:65:55
  wire        _canEnqueue_T_4 = _canEnqueue_T_3 <= 16'h40;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:65:{55,71}
  assign canEnqueue = _canEnqueue_T_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:65:{28,71}
  assign _body_io_in_0_T = _receiver_out_bits_bits[7:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :73:44
  assign _body_io_in_1_T = _receiver_out_bits_bits[15:8];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :73:44
  assign _body_io_in_2_T = _receiver_out_bits_bits[23:16];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :73:44
  assign _body_io_in_3_T = _receiver_out_bits_bits[31:24];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :73:44
  assign _body_io_in_4_T = _receiver_out_bits_bits[39:32];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :73:44
  assign _fifo_io_enq_bits_bits_T = {1'h0, _body_out};	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:59:20, :65:33, :78:43
  reg         fifo_io_enq_bits_last_r;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_2;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_3;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_5;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_6;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_7;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_8;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_9;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_10;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_11;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_12;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_13;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_14;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_15;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_16;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_17;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_18;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_19;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_20;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_21;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_22;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_23;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_24;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_25;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_26;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_27;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_28;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_29;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_bits_last_r_30;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
  reg         fifo_io_enq_valid_r;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_2;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_3;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_5;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_6;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_7;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_8;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_9;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_10;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_11;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_12;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_13;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_14;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_15;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_16;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_17;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_18;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_19;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_20;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_21;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_22;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_23;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_24;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_25;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_26;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_27;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_28;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_29;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  reg         fifo_io_enq_valid_r_30;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  wire        _itemCountInPipeline_T = canEnqueue & _receiver_out_valid;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :75:22, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        _itemCountInPipeline_T_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:87:10
  assign _itemCountInPipeline_T_1 = _itemCountInPipeline_T;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:87:10, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire [16:0] _itemCountInPipeline_T_2 =
    {1'h0, itemCountInPipeline} + {16'h0, _itemCountInPipeline_T_1};	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36, :65:33, :87:{5,10}
  wire [15:0] _itemCountInPipeline_T_3 = _itemCountInPipeline_T_2[15:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:87:5
  wire        _itemCountInPipeline_T_4 = canEnqueue & _receiver_out_valid;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :75:22, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        _itemCountInPipeline_T_5;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:88:10
  assign _itemCountInPipeline_T_5 = _itemCountInPipeline_T_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:88:10, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire [16:0] _itemCountInPipeline_T_6 =
    {1'h0, _itemCountInPipeline_T_3} - {16'h0, _itemCountInPipeline_T_5};	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36, :65:33, :87:5, :88:{5,10}
  wire [15:0] _itemCountInPipeline_T_7 = _itemCountInPipeline_T_6[15:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:88:5
  always @(posedge clock) begin
    if (reset)
      itemCountInPipeline <= 16'h0;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36
    else
      itemCountInPipeline <= _itemCountInPipeline_T_7;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36, :88:5
  end // always @(posedge)
  always @(posedge clock) begin
    fifo_io_enq_bits_last_r <= _receiver_out_bits_last;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :79:41
    fifo_io_enq_bits_last_r_1 <= fifo_io_enq_bits_last_r;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_2 <= fifo_io_enq_bits_last_r_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_3 <= fifo_io_enq_bits_last_r_2;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_4 <= fifo_io_enq_bits_last_r_3;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_5 <= fifo_io_enq_bits_last_r_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_6 <= fifo_io_enq_bits_last_r_5;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_7 <= fifo_io_enq_bits_last_r_6;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_8 <= fifo_io_enq_bits_last_r_7;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_9 <= fifo_io_enq_bits_last_r_8;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_10 <= fifo_io_enq_bits_last_r_9;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_11 <= fifo_io_enq_bits_last_r_10;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_12 <= fifo_io_enq_bits_last_r_11;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_13 <= fifo_io_enq_bits_last_r_12;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_14 <= fifo_io_enq_bits_last_r_13;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_15 <= fifo_io_enq_bits_last_r_14;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_16 <= fifo_io_enq_bits_last_r_15;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_17 <= fifo_io_enq_bits_last_r_16;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_18 <= fifo_io_enq_bits_last_r_17;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_19 <= fifo_io_enq_bits_last_r_18;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_20 <= fifo_io_enq_bits_last_r_19;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_21 <= fifo_io_enq_bits_last_r_20;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_22 <= fifo_io_enq_bits_last_r_21;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_23 <= fifo_io_enq_bits_last_r_22;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_24 <= fifo_io_enq_bits_last_r_23;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_25 <= fifo_io_enq_bits_last_r_24;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_26 <= fifo_io_enq_bits_last_r_25;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_27 <= fifo_io_enq_bits_last_r_26;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_28 <= fifo_io_enq_bits_last_r_27;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_29 <= fifo_io_enq_bits_last_r_28;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_30 <= fifo_io_enq_bits_last_r_29;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_bits_last_r_31 <= fifo_io_enq_bits_last_r_30;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
    fifo_io_enq_valid_r <= _receiver_out_valid;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:56:24, :80:37
    fifo_io_enq_valid_r_1 <= fifo_io_enq_valid_r;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_2 <= fifo_io_enq_valid_r_1;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_3 <= fifo_io_enq_valid_r_2;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_4 <= fifo_io_enq_valid_r_3;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_5 <= fifo_io_enq_valid_r_4;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_6 <= fifo_io_enq_valid_r_5;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_7 <= fifo_io_enq_valid_r_6;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_8 <= fifo_io_enq_valid_r_7;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_9 <= fifo_io_enq_valid_r_8;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_10 <= fifo_io_enq_valid_r_9;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_11 <= fifo_io_enq_valid_r_10;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_12 <= fifo_io_enq_valid_r_11;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_13 <= fifo_io_enq_valid_r_12;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_14 <= fifo_io_enq_valid_r_13;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_15 <= fifo_io_enq_valid_r_14;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_16 <= fifo_io_enq_valid_r_15;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_17 <= fifo_io_enq_valid_r_16;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_18 <= fifo_io_enq_valid_r_17;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_19 <= fifo_io_enq_valid_r_18;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_20 <= fifo_io_enq_valid_r_19;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_21 <= fifo_io_enq_valid_r_20;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_22 <= fifo_io_enq_valid_r_21;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_23 <= fifo_io_enq_valid_r_22;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_24 <= fifo_io_enq_valid_r_23;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_25 <= fifo_io_enq_valid_r_24;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_26 <= fifo_io_enq_valid_r_25;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_27 <= fifo_io_enq_valid_r_26;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_28 <= fifo_io_enq_valid_r_27;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_29 <= fifo_io_enq_valid_r_28;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_30 <= fifo_io_enq_valid_r_29;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
    fifo_io_enq_valid_r_31 <= fifo_io_enq_valid_r_30;	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
  end // always @(posedge)
  `ifndef SYNTHESIS	// <unknown>:298:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <unknown>:298:10
      `FIRRTL_BEFORE_INITIAL	// <unknown>:298:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <unknown>:298:10
      automatic logic [31:0] _RANDOM_0;	// <unknown>:298:10
      automatic logic [31:0] _RANDOM_1;	// <unknown>:298:10
      automatic logic [31:0] _RANDOM_2;	// <unknown>:298:10
      `ifdef INIT_RANDOM_PROLOG_	// <unknown>:298:10
        `INIT_RANDOM_PROLOG_	// <unknown>:298:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <unknown>:298:10
        _RANDOM_0 = `RANDOM;	// <unknown>:298:10
        _RANDOM_1 = `RANDOM;	// <unknown>:298:10
        _RANDOM_2 = `RANDOM;	// <unknown>:298:10
        itemCountInPipeline = _RANDOM_0[15:0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:64:36
        fifo_io_enq_bits_last_r = _RANDOM_0[16];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_1 = _RANDOM_0[17];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_2 = _RANDOM_0[18];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_3 = _RANDOM_0[19];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_4 = _RANDOM_0[20];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_5 = _RANDOM_0[21];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_6 = _RANDOM_0[22];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_7 = _RANDOM_0[23];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_8 = _RANDOM_0[24];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_9 = _RANDOM_0[25];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_10 = _RANDOM_0[26];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_11 = _RANDOM_0[27];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_12 = _RANDOM_0[28];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_13 = _RANDOM_0[29];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_14 = _RANDOM_0[30];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_15 = _RANDOM_0[31];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_16 = _RANDOM_1[0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_17 = _RANDOM_1[1];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_18 = _RANDOM_1[2];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_19 = _RANDOM_1[3];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_20 = _RANDOM_1[4];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_21 = _RANDOM_1[5];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_22 = _RANDOM_1[6];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_23 = _RANDOM_1[7];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_24 = _RANDOM_1[8];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_25 = _RANDOM_1[9];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_26 = _RANDOM_1[10];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_27 = _RANDOM_1[11];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_28 = _RANDOM_1[12];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_29 = _RANDOM_1[13];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_30 = _RANDOM_1[14];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_bits_last_r_31 = _RANDOM_1[15];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:79:41
        fifo_io_enq_valid_r = _RANDOM_1[16];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_1 = _RANDOM_1[17];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_2 = _RANDOM_1[18];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_3 = _RANDOM_1[19];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_4 = _RANDOM_1[20];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_5 = _RANDOM_1[21];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_6 = _RANDOM_1[22];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_7 = _RANDOM_1[23];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_8 = _RANDOM_1[24];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_9 = _RANDOM_1[25];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_10 = _RANDOM_1[26];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_11 = _RANDOM_1[27];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_12 = _RANDOM_1[28];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_13 = _RANDOM_1[29];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_14 = _RANDOM_1[30];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_15 = _RANDOM_1[31];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_16 = _RANDOM_2[0];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_17 = _RANDOM_2[1];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_18 = _RANDOM_2[2];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_19 = _RANDOM_2[3];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_20 = _RANDOM_2[4];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_21 = _RANDOM_2[5];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_22 = _RANDOM_2[6];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_23 = _RANDOM_2[7];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_24 = _RANDOM_2[8];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_25 = _RANDOM_2[9];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_26 = _RANDOM_2[10];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_27 = _RANDOM_2[11];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_28 = _RANDOM_2[12];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_29 = _RANDOM_2[13];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_30 = _RANDOM_2[14];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
        fifo_io_enq_valid_r_31 = _RANDOM_2[15];	// home/jsch/projects/mthesis/ChiselSPNController/src/main/scala/spn/SPNController.scala:80:37
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <unknown>:298:10
      `FIRRTL_AFTER_INITIAL	// <unknown>:298:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
endmodule


