// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package spn_compiler.server.grpc.spncserver

/** The compile request consists of the SPN to compile (as JSON).
  */
@SerialVersionUID(0L)
final case class CompileRequest(
    spn: _root_.scala.Predef.String = ""
    ) extends scalapb.GeneratedMessage with scalapb.Message[CompileRequest] with scalapb.lenses.Updatable[CompileRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = spn
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = spn
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): spn_compiler.server.grpc.spncserver.CompileRequest = {
      var __spn = this.spn
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __spn = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      spn_compiler.server.grpc.spncserver.CompileRequest(
          spn = __spn
      )
    }
    def withSpn(__v: _root_.scala.Predef.String): CompileRequest = copy(spn = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = spn
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(spn)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = spn_compiler.server.grpc.spncserver.CompileRequest
}

object CompileRequest extends scalapb.GeneratedMessageCompanion[spn_compiler.server.grpc.spncserver.CompileRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[spn_compiler.server.grpc.spncserver.CompileRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): spn_compiler.server.grpc.spncserver.CompileRequest = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    spn_compiler.server.grpc.spncserver.CompileRequest(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[spn_compiler.server.grpc.spncserver.CompileRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      spn_compiler.server.grpc.spncserver.CompileRequest(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SpncserverProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SpncserverProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = spn_compiler.server.grpc.spncserver.CompileRequest(
  )
  implicit class CompileRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, spn_compiler.server.grpc.spncserver.CompileRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, spn_compiler.server.grpc.spncserver.CompileRequest](_l) {
    def spn: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.spn)((c_, f_) => c_.copy(spn = f_))
  }
  final val SPN_FIELD_NUMBER = 1
  def of(
    spn: _root_.scala.Predef.String
  ): _root_.spn_compiler.server.grpc.spncserver.CompileRequest = _root_.spn_compiler.server.grpc.spncserver.CompileRequest(
    spn
  )
}
