// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package spn_compiler.server.grpc.spncserver

object SpncserverProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      spn_compiler.server.grpc.spncserver.CompileRequest,
      spn_compiler.server.grpc.spncserver.CompileReply
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChBzcG5jc2VydmVyLnByb3RvEgZwYXJzZXIiLAoOQ29tcGlsZVJlcXVlc3QSGgoDc3BuGAEgASgJQgjiPwUSA3NwblIDc3BuI
  jYKDENvbXBpbGVSZXBseRImCgdtZXNzYWdlGAEgASgJQgziPwkSB21lc3NhZ2VSB21lc3NhZ2UykwEKC1NQTkNvbXBpbGVyEkEKD
  1NQTkNvbXBpbGVfSlNPThIWLnBhcnNlci5Db21waWxlUmVxdWVzdBoULnBhcnNlci5Db21waWxlUmVwbHkiABJBCg9TUE5Db21wa
  WxlX1RleHQSFi5wYXJzZXIuQ29tcGlsZVJlcXVlc3QaFC5wYXJzZXIuQ29tcGlsZVJlcGx5IgBCOgoYc3BuX2NvbXBpbGVyLnNlc
  nZlci5ncnBjQhBTUE5Db21waWxlclByb3RvUAGiAglTUE5DUFJPVE9iBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}