cmake -G Ninja ../llvm \
    -DLLVM_ENABLE_PROJECTS="mlir;clang;compiler-rt" \
    -DLLVM_TARGETS_TO_BUILD="host" \
    -DBUILD_SHARED_LIBS=ON \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_BUILD_TYPE=DEBUG \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DLLVM_ENABLE_RTTI=ON 
