name: build-and-test-xspn
on: [push]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          cd xspn
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m pytest
