name: build-and-test-xspn
on: [push]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        run: |
          sudo apt update
          sudo apt -y install python3 python3-venv python3-pip
          python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          env | grep VIRTUAL_ENV | wc -l
          cd xspn
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m pytest
